name: その日の間状態を引継ぐ
# 5分毎実行し、成功したらその日はもう処理をskipする

on:
  # schedule:
  #   - cron: '5 * * * *' # UTCなので+9してJSTにする
  workflow_dispatch:
env:
  # キャッシュを強制クリアしたいときに任意の番号に変更してください
  CACHE-VERSION: a83dbc6
  DAILY-STATE-FILE: ~/tmp/daily-state.txt

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.7.0]
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Cache daily state
        id: daily_state
        uses: actions/cache@v3
        with:
          path: |
            ${{env.DAILY-STATE-FILE}}
          key: run-state-${{ steps.date.outputs.date }}-${{env.CACHE-VERSION}}
          restore-keys: |
            run-state-
      - name: show state
        id: save-state
        run: |
          cat ${{env.DAILY-STATE-FILE}}
      - name: save state
        id: save-state
        run: |
          echo "success! ${{ steps.date.outputs.date }}" > ${{env.DAILY-STATE-FILE}}
